import type { AICommit, DetectionMethod } from "./types.js";

interface RawCommit {
	hash: string;
	shortHash: string;
	subject: string;
	authorEmail: string;
	date: string;
	coAuthorRaw: string;
}

/** Known AI co-author email patterns. */
const AI_EMAIL_PATTERNS: Array<{ pattern: RegExp; tool: string; nameRequired?: RegExp }> = [
	{ pattern: /noreply@anthropic\.com/i, tool: "claude" },
	{ pattern: /noreply@github\.com/i, tool: "copilot", nameRequired: /copilot/i },
	{ pattern: /cursor/i, tool: "cursor" },
	{ pattern: /devin/i, tool: "devin" },
	{ pattern: /aider/i, tool: "aider" },
];

/** Commit message patterns that suggest AI involvement. */
const MESSAGE_PATTERNS = /generated by|co-authored-by.*claude|🤖|bot:/i;

/**
 * Parse NUL-delimited git log output into structured commits.
 * Expected format per line:
 *   %H\0%h\0%s\0%ae\0%aI\0%(trailers:key=Co-authored-by,valueonly,separator=\x1E)
 */
export function parseGitLog(output: string): RawCommit[] {
	const lines = output.trim().split("\n");
	const commits: RawCommit[] = [];

	for (const line of lines) {
		if (!line.trim()) continue;

		const fields = line.split("\0");
		if (fields.length < 5) continue;

		commits.push({
			hash: fields[0],
			shortHash: fields[1],
			subject: fields[2],
			authorEmail: fields[3],
			date: fields[4],
			coAuthorRaw: fields[5] ?? "",
		});
	}

	return commits;
}

/**
 * Parse co-author trailer values into individual entries.
 * Input format: "Name <email>" separated by \x1E (record separator).
 */
function parseCoAuthors(raw: string): Array<{ name: string; email: string }> {
	if (!raw.trim()) return [];

	return raw.split("\x1E").flatMap((entry) => {
		const match = /^(.+?)\s*<(.+?)>/.exec(entry.trim());
		if (!match) return [];
		return [{ name: match[1].trim(), email: match[2].trim() }];
	});
}

/**
 * Check if a co-author list contains known AI tool patterns.
 * Returns the matched tool name or null.
 */
function matchCoAuthorAI(coAuthors: Array<{ name: string; email: string }>): string | null {
	for (const author of coAuthors) {
		for (const { pattern, tool, nameRequired } of AI_EMAIL_PATTERNS) {
			if (pattern.test(author.email)) {
				if (nameRequired && !nameRequired.test(author.name)) continue;
				return tool;
			}
			if (pattern.test(author.name)) return tool;
		}
	}
	return null;
}

/**
 * Check if an author email matches known AI bot patterns.
 */
function matchAuthorEmailAI(email: string): boolean {
	for (const { pattern } of AI_EMAIL_PATTERNS) {
		if (pattern.test(email)) return true;
	}
	return false;
}

/**
 * Detect AI signals on a single commit. Returns detection method + confidence,
 * or null if no AI signal detected.
 */
export function detectSignals(
	commit: RawCommit,
): { method: DetectionMethod; confidence: number } | null {
	const coAuthors = parseCoAuthors(commit.coAuthorRaw);
	let bestMethod: DetectionMethod | null = null;
	let bestConfidence = 0;

	// 1. Co-author tag match (confidence 0.9)
	if (matchCoAuthorAI(coAuthors)) {
		bestMethod = "co-author-tag";
		bestConfidence = 0.9;
	}

	// 2. Author email match (confidence 0.8)
	if (matchAuthorEmailAI(commit.authorEmail) && 0.8 > bestConfidence) {
		bestMethod = "author-email";
		bestConfidence = 0.8;
	}

	// 3. Message pattern match (confidence 0.6)
	if (MESSAGE_PATTERNS.test(commit.subject) && 0.6 > bestConfidence) {
		bestMethod = "message-pattern";
		bestConfidence = 0.6;
	}

	if (bestMethod) {
		return { method: bestMethod, confidence: bestConfidence };
	}
	return null;
}

/**
 * Get diff stats for a commit relative to its parent.
 * Returns file list + addition/deletion counts.
 */
async function getDiffStats(
	repoPath: string,
	hash: string,
): Promise<{
	filesChanged: string[];
	diffStat: { additions: number; deletions: number; filesChanged: number };
} | null> {
	const proc = Bun.spawn(["git", "diff", "--numstat", `${hash}^..${hash}`], {
		cwd: repoPath,
		stdout: "pipe",
		stderr: "pipe",
	});

	const exitCode = await proc.exited;
	if (exitCode !== 0) return null;

	const stdout = await new Response(proc.stdout).text();
	const lines = stdout.trim().split("\n").filter(Boolean);

	const files: string[] = [];
	let totalAdd = 0;
	let totalDel = 0;

	for (const line of lines) {
		const parts = line.split("\t");
		if (parts.length < 3) continue;
		const add = Number.parseInt(parts[0], 10) || 0;
		const del = Number.parseInt(parts[1], 10) || 0;
		totalAdd += add;
		totalDel += del;
		files.push(parts[2]);
	}

	return {
		filesChanged: files,
		diffStat: {
			additions: totalAdd,
			deletions: totalDel,
			filesChanged: files.length,
		},
	};
}

/**
 * Detect AI-involved commits in a git repository.
 */
export async function detectAICommits(
	repoPath: string,
	options?: { since?: string; until?: string; commit?: string },
): Promise<{
	commits: AICommit[];
	scanned: number;
	skipped: Array<{ hash: string; reason: string }>;
}> {
	const args = [
		"git",
		"log",
		"--format=%H%x00%h%x00%s%x00%ae%x00%aI%x00%(trailers:key=Co-authored-by,valueonly,separator=%x1E)",
	];

	if (options?.commit) {
		args.push("-1", options.commit);
	} else {
		if (options?.since) args.push(`--since=${options.since}`);
		if (options?.until) args.push(`--until=${options.until}`);
	}

	const proc = Bun.spawn(args, {
		cwd: repoPath,
		stdout: "pipe",
		stderr: "pipe",
	});

	const exitCode = await proc.exited;
	if (exitCode !== 0) {
		const stderr = await new Response(proc.stderr).text();
		throw new Error(`git log failed: ${stderr.trim()}`);
	}

	const stdout = await new Response(proc.stdout).text();
	const rawCommits = parseGitLog(stdout);
	const commits: AICommit[] = [];
	const skipped: Array<{ hash: string; reason: string }> = [];

	for (const raw of rawCommits) {
		const signal = detectSignals(raw);
		if (!signal) continue;

		// Check if this is the initial commit (no parent)
		const parentCheck = Bun.spawn(["git", "rev-parse", "--verify", `${raw.hash}^`], {
			cwd: repoPath,
			stdout: "pipe",
			stderr: "pipe",
		});
		const parentExit = await parentCheck.exited;
		if (parentExit !== 0) {
			skipped.push({ hash: raw.shortHash, reason: "no parent commit" });
			continue;
		}

		const diff = await getDiffStats(repoPath, raw.hash);
		if (!diff || diff.filesChanged.length === 0) {
			skipped.push({ hash: raw.shortHash, reason: "empty diff" });
			continue;
		}

		const coAuthors = parseCoAuthors(raw.coAuthorRaw);

		commits.push({
			hash: raw.hash,
			shortHash: raw.shortHash,
			message: raw.subject,
			author: raw.authorEmail,
			coAuthors: coAuthors.map((a) => `${a.name} <${a.email}>`),
			detectionMethod: signal.method,
			confidence: signal.confidence,
			timestamp: new Date(raw.date),
			filesChanged: diff.filesChanged,
			diffStat: diff.diffStat,
		});
	}

	return { commits, scanned: rawCommits.length, skipped };
}
